import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'delDSL dashboard',
  description: 'Generated by delDSL',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
<<<<<<< HEAD
      <link rel="icon" href="/favicon_1.ico" sizes="any"/>
=======
      <link rel="icon" href="/favicon.ico" sizes="any"/>
>>>>>>> 6b906fbbc382624ae9336065dcc4a880ca66c17e
      </head>
      
      <body className={inter.className}>{children}</body>
    </html>
  )
}
